firstproject/emailapp/urls.py
from unicodedata import name
from django.urls import path
from .views import *
urlpatterns=[
    path('emails/',mail,name='em'),
    path('flup/',flup,name='flup'),
    
]

firstproject/firstproject/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from userapp.views import log
urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/',include('userapp.urls')),
    path('emailapp/',include('emailapp.urls')),
    path('',log,name='log')
]

firstproject/userapp/urls.py
from unicodedata import name
from django.urls import path
from .views import forms,modelform,form3, userreg,home,userreg2,viewdata,deletstud,updatestud,setcookie,getcookie
urlpatterns = [
     path('form/',forms,name='form1'),
    path('modelform/',modelform,name='form2'),
    path('form3/',form3,name='form3'),
    path('viewdata/',viewdata,name='view'),
    path('deletestud/<uid>',deletstud,name='delet'),
    path('updatestud/<uid>',updatestud,name='updat'),
    path('userreg/',userreg,name='userreg'),
    path('userreg2/',userreg2,name='userreg2'),
    path('home/', home,name='h'),
    path('setcookie/',setcookie,name='set'),
    path('getcookie/',getcookie,name='get'),
]

firstproject/emailapp/models.py
from django.db import models

# Create your models here.

firstproject/userapp/models.py
from asyncio.windows_events import NULL
from tabnanny import verbose
from unicodedata import name
from django.db import models

class Students(models.Model):
    name=models.CharField(max_length=100,verbose_name='Student_name')
    age=models.IntegerField()
    phone=models.CharField(max_length=25)
    email=models.EmailField()
    address=models.CharField(max_length=28,default=NULL)
    
class Teacher(models.Model):
     name=models.CharField(max_length=100,verbose_name='Student_name')
     age=models.IntegerField()
class Books(models.Model):
    name=models.CharField(verbose_name='book name',max_length=100)
    price=models.IntegerField()
    author=models.CharField(max_length=100)
    class Meta:
        db_table='Book'
        

firstproject/emailapp/forms.py
from django import forms
class Filesup(forms.Form):
    file=forms.FileField()
    

firstproject/userapp/forms.py
from dataclasses import fields
from importlib.metadata import files
from pyexpat import model

from unicodedata import name
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Books
class studentform(forms.Form):
    name=forms.CharField(max_length=100)
    age=forms.IntegerField()
    email=forms.EmailField()
class Bookform(forms.ModelForm):
    class Meta:
        model=Books
        fields="__all__"
        ##add it as tuple string which all to display 
class regform(UserCreationForm):
    class Meta:
        model=User
        fields=('first_name','last_name','email','username','password1','password2')
    

firstproject/emailapp/views.py
from django import http
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from .forms import *
# Create your views here.
def mail(request):
    subject="greetings"
    msg="congrats on ur registration"
    to="nibingunnerzz1111@gmail.com"
    res=send_mail(subject,msg,settings.EMAIL_HOST_USER,[to])
    if res==1:
        m="Mail success"
    else:
        m='mailing failed'
    return HttpResponse(m)        
def flup(request):
    if request.method=='GET':
         context={}
         context['form']=Filesup()
         return render(request,'fileup.html',context)
    elif request.method=='POST':
        fp=Filesup(request.POST,request.FILES)
        if fp.is_valid():
            fil=request.FILES['file']
            handle_method(fil)
            return HttpResponse('fileuploaded')
def handle_method(f):
    with open('emailapp\\static\\upload\\'+f.name,'wb+') as dest:
        for c in f.chunks():
            dest.write(c)
    
        
   

firstproject/userapp/views.py
import imp
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .forms import studentform,Bookform,regform
from .models import Students
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login
def home(request):
        request.session['user']='Rahul'
        return render(request,'home.html')
def setcookie(request):
    res=HttpResponse('cookie set')
    res.set_cookie('Quest','Pythonintersnhip')
    return res
def getcookie(request):
    t=request.COOKIES['Quest']
    return HttpResponse('COOKIEname:'+t)     
def forms(request):
    student=studentform()
    a=['apple','banana','orange']
    return render(request,'studentform.html',{'formview':student,'listvar':a})
def modelform(request):
    if request.method=='GET':
         mform=Bookform()
         dct={}
         dct['mfor']=mform
         return render(request,'mform.html',dct)
    elif request.method=='POST':
        b=Bookform(request.POST)
        print(b)
        if b.is_valid():
            b.save()
        return render(request,'mform.html')
def form3(request):
    if request.method=='GET':
         return render(request,'thirdform.html')
    elif request.method=='POST':
        name=request.POST['name']
        age=request.POST['age']
        address=request.POST['address']
        email=request.POST['email']
        phone=request.POST['phone'] 
        a=Students.objects.create(name=name,age=age,phone=phone,email=email,address=address)
        return redirect('form3')
def viewdata(request):
    a=Students.objects.all
    context={}
    context['data']=a
    context['uu']=request.session['user']
    return render(request,'viewdata.html',context)
def deletstud(request,uid):
    request.session['suid']=uid
    #sessionbuilding
    a=Students.objects.filter(id=uid).delete()
    return redirect('view')
def updatestud(request,uid):
    if request.method=='GET':
        a=Students.objects.get(id=uid)
        context={}
        context['sdata']=a
        return render(request,'editdata.html',context)
    elif request.method=='POST':
         name=request.POST['name']
         age=request.POST['age']
         address=request.POST['address']
         email=request.POST['email']
         phone=request.POST['phone'] 
         obk=Students.objects.filter(~Q(age=20)) #used for not equal to 20
         obk=Students.objects.filter(Q(age=20)&Q(name='Nibin')) #and operator
         obk=Students.objects.filter(Q(age=20)|Q(name='Nibin')) #or operator
         ob=Students.objects.filter(id=uid).update(name=name,age=age,phone=phone,email=email,address=address)
         return redirect('view')
def userreg(request):
    if request.method=='GET':
         context={}
         context['form']=regform()
         return render(request,'userreg.html',context)
    elif request.method=='POST':
        form=regform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('h')
   
def userreg2(request):
    if request.method=='GET':
         return render(request,'reg1form.html')
    else:
        uname=request.POST['user']
        p1=request.POST['pass1']
        p2=request.POST['pass2']
        if p1==p2:
            a=User.objects.create_user(username=uname,password=p1)
            return redirect('h') 

def log(request):
    if request.method=='GET':
        context={}
        context['form']=AuthenticationForm()
        return render(request,'login.html',context)
    elif request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.cleaned_data.get('username')
            pwd=form.cleaned_data.get('password')
            user=authenticate(request,username=user,password=pwd)
            if user:
                login(request,user)
                return redirect('h')
            else:
                print(form.errors)
                return redirect('log')
                    
    

firstproject/emailapp/templates/fileup.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      <form action="" enctype="multipart/form-data" >
          {%csrf_token%}
          {{form.as_p}}
          <p>
              <button type="submit" class="btn btn-success">upload</button>
          </p>
      </form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

firstproject/userapp/templates/editdata.html
{%extends 'home.html'%} 
{%block content%} 
<form method="post" class="text-center" >
    {% csrf_token %}
    <input class="form-control" placeholder="name" value="{{sdata.name}}" name="name" type="text">
    <input class="form-control" name="phone"  type="number" value="{{sdata.phone}}" placeholder="phone">
    <input type="text" name="address" class="form-control" value="{{sdata.address}}" placeholder="address">
    <input type="number" name="age" class="form-control" value="{{sdata.age}}" placeholder="age">
    <input type="email" name="email" class="form-control" value="{{sdata.email}}" placeholder="email">
    <button type="submit" class="btn btn-success">submit</button>
</form>
{%endblock content%} 

firstproject/userapp/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <ul class="nav bg-success">
    <li class="nav-item"><a href="{% url  'form1' %}" class="nav-link text-light">djangoform </a></li>
    <li class="nav-item"><a href="{% url  'form2' %}" class="nav-link text-light">modelform</a></li>
    <li class="nav-item"><a href="{% url  'form3' %}" class="nav-link text-light">modelform</a></li>
    <li class="nav-item"><a href="{% url  'view' %}" class="nav-link text-light">view data</a></li> 
    <li class="nav-item"><a href="{% url  'userreg' %}" class="nav-link text-light">userreg</a></li>
    <li class="nav-item"><a href="{% url  'userreg2' %}" class="nav-link text-light">userreg2</a></li>
    
  </ul> 
  
  <h1>django project</h1>

     {%block content%}
     <h1>form1</h1>
     {%endblock content%}

    {%block index%}
    <h1>form2</h1>
    {%endblock index%}
  </body>
     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
 
</html> 

firstproject/userapp/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
     <form action="" >
         {%csrf_token%}
         {{form.as_table}}
         <tr><td colspan="2" class="text-center"><button class="btn btn-success" type="submit">login</button> </td></tr>
     </form> 
    <!-- Optional JavaScript -->
    
  </body>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

firstproject/userapp/templates/mform.html
 {%extends 'home.html'%} 
 {%block content%}
    <table class="table table-dark">
    <form action="post">
     {% csrf_token %}
        {{mfor.as_table}}
        <tr><td colspan="2" class="text-center">
            <button class="btn btn-success" type="submit">Add</button>
        </td> </tr>
    </form>
    </table>    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   
  <script>
      $('#id_name').attr('class','form-control')
      $('#id_price').attr('class','form-control')
      $('#id_author').attr('class','form-control')
  </script>
{%endblock content%}

firstproject/userapp/templates/reg1form.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <form action="">
        {%csrf_token%}
        <input type="text" name="user" placeholder="username"><br>
        <input type="text" name="pass1" placeholder="password"><br>
        <input type="text" name="pass2" placeholder="confirmpassword"><br>
    </form>  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
</html>

firstproject/userapp/templates/studentform.html
    {%extends 'home.html'%}
       {%block index%}
        <p>django</p>
    <table>  {{formview.as_table}}</table>
   {%for i in listvar%} 
   <p>{{i}}</p>
   {%endfor%}
   {%if 'apple' in listvar%} 
   <h4>apple is in the list</h4>
   {%endif%}    
  
 {%endblock index%}

firstproject/userapp/templates/thirdform.html
{%extends 'home.html'%} 
{%block content%} 
<form method="post" class="text-center" >
    {% csrf_token %}
    <input class="form-control" placeholder="name" name="name" type="text">
    <input class="form-control" name="phone"  type="number" placeholder="phone">
    <input type="text" name="address" class="form-control" placeholder="address">
    <input type="number" name="age" class="form-control" placeholder="age">
    <input type="email" name="email" class="form-control" placeholder="email">
    <button type="submit" class="btn btn-success">submit</button>
</form>
{%endblock content%} 

firstproject/userapp/templates/userreg.html
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
  <table class="table table-dark"> 
      <form action="" method="post">
          {%csrf_token%}
          {{form.as_table}}
         <tr><td colspan="2" class="text-center"><button type="submit" class="btn btn-success">submit</button></td></tr>
      </form>
  </table>    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
  </body>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

firstproject/userapp/templates/viewdata.html
{%extends 'home.html' %}
{%block content%}
<table class="table table-bordered table-dark">
<thead>
    <h3>{{user}}</h3>
    <tr>
        <th>name</th>
        <th>age</th>
        <th>phone</th>
        <th>email</th>
        <th>address</th>

    </tr>
</thead>
<tbody>
    {%for i in data%}
    <tr>
        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.phone}}</td>
        <td>{{i.email}}</td>
        <td>{{i.address}}</td>
        <td><a class="btn btn-danger" href="{%url 'delet' i.id%}">delete</a></td>
        <td><a class="btn btn-primary" href="{%url 'updat' i.id%}">update</a></td>
    </tr>
    {%endfor%}
</tbody>
</table>
{%endblock content%}